### ISSUE TITLE
Cannot install on Ubuntu Server 22.04

### ISSUE THREAD

**Issue by KC0HYI** [ShaYmez/hblink3-docker-install#3]
Good evening.

I am attempting to get your stack installed on a fresh instance of Ubuntu Server 22.04 running on AWS and get the following:

**------------------------------------------------------------------------------
Downloading and installing required software & dependencies.....
------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------
Operating system not supported! Please check your configuration or upgrade. Exiting.....
-------------------------------------------------------------------------------------------**

The instance I am running is 2 CPUs, 4GB of RAM and 24GB of disk and I'm running the installer as 'root'.  

Is there something obvious which I'm missing?

Thank you!
GB.

**Comment by ShaYmez** [comment]
Fixed… Now supports 22.04 bookworm. Perform git pull or re-clone the updated repo hblink3-docker-install.git ThanksShaYmezM0VUB On 18 Feb 2024, at 01:51, KC0HYI ***@***.***> wrote:﻿
Good evening.
I am attempting to get your stack installed on a fresh instance of Ubuntu Server 22.04 running on AWS and get the following:
**------------------------------------------------------------------------------
Downloading and installing required software & dependencies.....

Operating system not supported! Please check your configuration or upgrade. Exiting.....
-------------------------------------------------------------------------------------------**
The instance I am running is 2 CPUs, 4GB of RAM and 24GB of disk and I'm running the installer as 'root'.
Is there something obvious which I'm missing?
Thank you!
GB.

**Comment by KC0HYI** [comment]
Thank you VERY much - that works perfectly!!  I appreciate your update!  Have a GREAT rest of your weekend  //gb
